### PR TITLE
completed form for new posts in PostCreate.jsx

### PR DESCRIPTION
**Pull request by navedrahim**
created form for new posts

### CODE REVIEW

**Review by Gino2B — APPROVED** [review]

**Review by flexibleidealist — CHANGES_REQUESTED** [review]
Great work, Naved. Please change the handle submit to reflect the changes we discussed in stand up.

**Review by Gino2B — CHANGES_REQUESTED** [review]
CHANGES

**Review by Gino2B — APPROVED** [review]
Looks great

**Review by flexibleidealist — APPROVED** [review]
awesome

**Pull request merged**
